InAndOut/Models/ExpenseCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models
{
    public class ExpenseCategory
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("Category Name")]
        public string CategoryName { get; set; }
    }
}

InAndOut/Controllers/ExpenseCategoryController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ExpenseCategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpenseCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<ExpenseCategory> objList = _db.ExpensesCategories;
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenseCategory obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpensesCategories.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("index");
            }

            return View(obj);
        }
        
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var obj = _db.ExpensesCategories.Find(id);

            if (obj == null)
                return NotFound();

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.ExpensesCategories.Find(id);

            if (obj == null)
                return NotFound();

            _db.ExpensesCategories.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var obj = _db.ExpensesCategories.Find(id);

            if (obj == null)
                return NotFound();

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Update(ExpenseCategory obj)
        {
            if (ModelState.IsValid)
            {
                _db.ExpensesCategories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

InAndOut/Views/ExpenseCategory/Create.cshtml
@model InAndOut.Models.ExpenseCategory

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*@<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Create a new Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="CategoryName"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group rouw">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/ExpenseCategory/Delete.cshtml
@model InAndOut.Models.ExpenseCategory

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*@<div asp-validation-summary="All" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="CategoryName"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="CategoryName" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group rouw">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/ExpenseCategory/Index.cshtml
@model IEnumerable<InAndOut.Models.ExpenseCategory>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Categorys of Expenses</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ExpenseCategory" asp-action="Create" class="btn btn-primary">Create a new Expense Type</a>
        </div>
    </div>
</div>
<br />

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
        <th>
            Category Name
        </th>
        <th>
            Changes
        </th>
        </thead>
        <tbody>
            @foreach (var expenseCategory in Model)
            {
                <tr>
                    <td width="35%">@expenseCategory.CategoryName</td>
                    <td width="30%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="ExpenseCategory" asp-action="Update" asp-route-Id="@expenseCategory.Id" class="btn btn-primary mx-1">Update</a>
                            <a asp-controller="ExpenseCategory" asp-action="Delete" asp-route-Id="@expenseCategory.Id" class="btn btn-danger mx-1">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No Expenses Registred Yet!</p>
}

InAndOut/Views/ExpenseCategory/Update.cshtml
@model InAndOut.Models.ExpenseCategory

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Category Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="CategoryName"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group rouw">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}