InAndOut/Controllers/ExpensesController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ExpensesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Expenses> objList = _db.Expenses;
            return View(objList);
        }

        //GET-CREATE    
        public IActionResult Create()
        {
            return View();
        }

        //POST-CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Expenses obj)
        {
            _db.Expenses.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

InAndOut/Views/Expenses/Create.cshtml
@model InAndOut.Models.Expenses

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpensesName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpensesName" class="form-control" />
                    </div> 
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                    </div>
                </div>
                <div class="form-group rouw">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create"/>
                        </div> 
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

InAndOut/Views/Expenses/Index.cshtml
@model IEnumerable<InAndOut.Models.Expenses>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expenses" asp-action="Create" class="btn btn-primary">Create a new expense</a>
        </div>
    </div>
</div>
<br/>

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <th>
                Expenses Name
            </th>
            <th>
                Amount
            </th>
        </thead>
        <tbody>
            @foreach (var expenses in Model)
            {
                <tr>
                    <td width="30%">@expenses.ExpensesName</td>
                    <td width="30%">@expenses.Amount</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No Expenses Registred Yet!</p>
}